name: Build HomeProxy IPK

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build IPK
        uses: immortalwrt/gh-action-sdk@master
        env:
          # 填入你的架构，例如 x86_64, aarch64_generic, mt7981 等
          ARCH: x86_64 
          # 依赖仓库
          EXTRA_FEEDS: |
            src-git luci https://github.com/immortalwrt/luci.git
            src-git packages https://github.com/immortalwrt/packages.git
          # 指定编译的包
          PACKAGES: luci-app-homeproxy
          # 这里的 FEED_DIR 设为 homeproxy 的源码地址
          FEEDNAME: homeproxy
          FEED_DIR: https://github.com/immortalwrt/homeproxy.git

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: homeproxy-ipk
          path: bin/packages/*/action/*.ipk
